### ISSUE TITLE
Windows Compatibility Issues

### ISSUE THREAD

**Issue by Alexander-Ludwig** [aws-samples/cloud9-to-power-vscode-blog#6]
I work in AWS Support and have been working with a customer regarding issues following the steps from the AWS Blog [1] to connect to a Cloud9 instance using Visual Studio Code on a Windows Machine.

--- Overview of Issue ---

To summarize the issue, the customer and I followed all the steps to configure the Cloud9 instance + Cloud Formation stack, installing Visual Studio Code with the required plugins and necessary AWS CLI + SSM extenstions installed on the Windows host machine. When we attempt to 

When we then attempted to Connect to Cloud9 from Visual Studio Code we observe the following error trace:

```
[14:40:05.626] Log Level: 2
[14:40:05.627] remote-ssh@0.76.1
[14:40:05.627] win32 x64
[14:40:05.637] SSH Resolver called for "ssh-remote+cloud9", attempt 1
[14:40:05.637] "remote.SSH.useLocalServer": false
[14:40:05.637] "remote.SSH.showLoginTerminal": true
[14:40:05.637] "remote.SSH.remotePlatform": {}
[14:40:05.637] "remote.SSH.path": undefined
[14:40:05.638] "remote.SSH.configFile": C:\Users\myusername\.ssh\config
[14:40:05.638] "remote.SSH.useFlock": true
[14:40:05.638] "remote.SSH.lockfilesInTmp": false
[14:40:05.638] "remote.SSH.localServerDownload": auto
[14:40:05.638] "remote.SSH.remoteServerListenOnSocket": false
[14:40:05.638] "remote.SSH.showLoginTerminal": true
[14:40:05.638] "remote.SSH.defaultExtensions": []
[14:40:05.638] "remote.SSH.loglevel": 2
[14:40:05.639] "remote.SSH.enableDynamicForwarding": true
[14:40:05.639] "remote.SSH.enableRemoteCommand": false
[14:40:05.639] "remote.SSH.serverPickPortsFromRange": {}
[14:40:05.639] "remote.SSH.serverInstallPath": {}
[14:40:05.669] SSH Resolver called for host: cloud9
[14:40:05.670] Setting up SSH remote "cloud9"
[14:40:05.692] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[14:40:05.699] Install and start server if needed
[14:40:06.798] Checking ssh with "ssh -V"
[14:40:06.906] > OpenSSH_for_Windo
[14:40:06.906] > ws_8.1p1, LibreSSL 3.0.2

[14:40:06.911] Using SSH config file "C:\Users\myusername\.ssh\config"
[14:40:06.912] Running script with connection command: ssh -T -D 60969 -F "C:\Users\myusername\.ssh\config" cloud9 bash
[14:40:06.916] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:40:07.416] > ]0;C:\WINDOWS\System32\cmd.exe
[14:40:07.417] Got some output, clearing connection timeout
[14:40:07.425] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> CreateProcessW failed error:2
> posix_spawnp: No such file or directory
> The process tried to write to a nonexistent pipe.
[14:40:08.720] "install" terminal command done
[14:40:08.720] Install terminal quit with output: posix_spawnp: No such file or directory
[14:40:08.721] Received install output: posix_spawnp: No such file or directory
[14:40:08.722] Failed to parse remote port from server output
[14:40:08.723] Resolver error: Error: 
	at Function.Create (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:586041)
	at Object.t.handleInstallOutput (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:584693)
	at Object.t.tryInstall (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:681846)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:644486
	at async Object.t.withShowDetailsEvent (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:647831)
	at async Object.t.resolve (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:645565)
	at async c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:722872
[14:40:08.734] ------
```

--- Apparent Cause of Issue ---

From the error trace above the specific error appears to be:

```
> CreateProcessW failed error:2
> posix_spawnp: No such file or directory
> The process tried to write to a nonexistent pipe.
```

The error output from the log indicates the error is with specific command being run by the plugin:

ssh -T -D 60969 -F "C:\Users\myusername\.ssh\config" cloud9 bash

This plugin appears to be launching the windows cmd and running commands from it. Running the same command from cmd produces precisely the error above.

After doing a fair bit of investigation into the cause of the error, I believe the issue is caused by the to issues invoking the `ssm-proxy.sh` shell script from the "ProxyCommand" in the config file which is used by OpenSSH.

As per [2][3], the ProxyCommand works by processing standard input and output for the specified remote host. I am assuming the purpose of the `ssm-proxy.sh` script is to establish a connection to the Cloud9 host using ssm, with some conditional checks to see if the host is started and start it if needed. Ultimately the SSM command will connect to the remote host through the terminal/cmd session.

What I believe is happening as per the error output we observe, is that there is some issue processing the standard io from the shell script being run. I am not familiar with the nuances of OpenSSH, but there seems to be some compatibility issue running the shell script in the Windows environment. Again, the Visual Studio Code plugin appears to run the ssh command from cmd, at least in my Windows environment I cannot run `sh -c "C:/Users/myusername/.ssh/ssm-proxy.sh %h %p` from cmd, or found any other way of getting the shellscript to run as expected with the Visual Studio Code plugin.

I was able to verify that I can successfully connect to Cloud9 using the following config file and "ProxyCommand " which directly calls the SSM command (which also works from cmd):

```
Host cloud9
    IdentityFile C:/Users/myusername/.ssh/id_rsa
    User ec2-user
    HostName i-XXXXXXXXXXXXXXXXXXX
    ProxyCommand aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p
```

This particular config does bypass the script's check to see if the Cloud9 instance is running, but demonstrates that the issue is not with Cloud9 and the SSM connectivity, but rather something to do with compatibility issues with the solution outlined in [1] for the Windows environment.

--- Requested Next Steps ---

Could you please assist with adding some additional resources to the Solution from [1] compatible for the Windows Environment?

For example, as per my understanding above the following would be helpful:

- Outline steps to get the SSH script working from the cmd
- Include a PowerShell script on this repo which provides the same base functionality as the `ssm-proxy.sh` script, which can then be run from the ProxyCommand.

Please let me know if you need any further information or if I can be of any further assistance. I have raised this request on a customer's behalf.

**Comment by srohit0** [comment]
> Running script with connection command: ssh -T -D 60969 -F "C:\Users\myusername\.ssh\config" cloud9 bash

The line above is looking or a bash terminal, that your machine does not have.

Install [git-bash](https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/Git-2.38.1-64-bit.exe) on windows machine machine to resolve and close.

**Comment by bitshop** [comment]
On Windows the ProxyCommand would be ssm-proxy.bat, not .sh I believe.  As srohit0 said you can likely get bash working properly on Windows as an alternative.

**Comment by cyril-nmpro** [comment]
Tried installing git-bash - same error!!!
Tried with ssm-proxy.bat - numerous other errors... had to modify the batch file for path reference to AWS CLI and SSM Plugin. Also had to create the aws profile via cli, instead of direct modifying the ~/.aws/config
